# Generated by Django 4.2.4 on 2023-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
