# Generated by Django 4.2.5 on 2023-09-21 09:06

import catstagram.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catstagramuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), catstagram.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='catstagramuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), catstagram.core.validators.validate_only_letters]),
        ),
    ]
