# Generated by Django 4.2.5 on 2023-09-21 12:43

import catstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_catstagramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catstagramuser',
            name='personal_photo',
            field=models.ImageField(default='asd', upload_to='account_photos/', validators=[catstagram.photos.validators.validate_file_less_than_5mb]),
            preserve_default=False,
        ),
    ]
