# Generated by Django 4.2.5 on 2023-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_catstagramuser_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catstagramuser',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('DoNotShow', 'Do not Show')], max_length=9),
        ),
    ]
