# Generated by Django 4.2.5 on 2023-09-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_catstagramuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catstagramuser',
            name='date_joined',
        ),
    ]
