# Generated by Django 4.2.5 on 2023-09-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_catstagramuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catstagramuser',
            name='personal_photo',
        ),
    ]
