# Generated by Django 4.2.4 on 2023-09-04 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_cat_slug'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('locations', models.CharField(max_length=30)),
                ('publication_date', models.DateField(auto_now=True)),
                ('tagged_cats', models.ManyToManyField(blank=True, to='cats.cat')),
            ],
        ),
    ]
