# Generated by Django 4.2.4 on 2023-09-07 14:53

import catstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cat_photos/', validators=[catstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
